### ISSUE TITLE
terralith addon not working with terralith 

### ISSUE THREAD

**Issue by ghost** [OutrightWings/treeplacer_mod#10]
hi im trying to grow custom terralith trees with the terralith addon for treeplacer and when i grow them there just the same vanilla trees in the custom biomes like the shield biome any help?

im using terralith version 2.4.11 and treeplacer version 1.1.0 and terralith addon version 1.2.0 

![image](https://github.com/OutrightWings/treeplacer_mod/assets/86117177/6c98097d-1344-475a-bd38-ee74b4c6e1ed)

**Comment by OutrightWings** [comment]
I did not make the terralith configuration addon- so I do not know what biomes should have what trees or even if they keep it perfectly updated. I would need you to check that sapling's config to confirm that it has an override for that biome.

**Comment by ghost** [comment]
oh ok sorry could you confirm the biome override that would be good!

**Comment by OutrightWings** [comment]
If I'm going to check it I need to know exactly what biome you are in and what sapling.

**Comment by ghost** [comment]
It was the shield biome or the apline_highland with birch tree and shield biome with ok tree though I thought it might of been a problem with this mod itself since the other one doesn’t seem to be workingOn 8 Jan 2024, at 17:16, lily ***@***.***> wrote:﻿
If I'm going to check it I need to know exactly what biome you are in and what sapling.

**Comment by ghost** [comment]
did you manage to find why it wasnt working?

**Comment by OutrightWings** [comment]
The sapling override listed in the addon does not appear in the slash command to be placed. For example: 
![image](https://github.com/OutrightWings/treeplacer_mod/assets/46290459/427ef4b1-97ea-459a-8077-097a3e74b247)
While the available two are neither of what its listed 
![image](https://github.com/OutrightWings/treeplacer_mod/assets/46290459/85ff0383-71bf-4e7b-8f76-1d9dd82a1686)

**Comment by OutrightWings** [comment]
Can confirm things were fine in the dark oak biome where their config is correct.

**Comment by OutrightWings** [comment]
I have no control of the Terralith addon
