### ISSUE TITLE
Vanilla Saplings not growing bop trees

### ISSUE THREAD

**Issue by WenXin20** [OutrightWings/treeplacer_mod#11]
Hello, I recently tried making a datapack to grow bop spruce & dark oak trees using vanilla saplings, but both sapling are just growing vanilla trees. The biome is `biomesoplenty:mediterranean_forest` and the feature is `biomesoplenty:spruce_poplar_tree`. I've also placed the zip file in `config/openloader/data`.

I've made plenty of datapacks before, so I'm not sure why this isn't working. Are you able to take a look to see if I missed something? Thanks.
[treeplacer_compat.zip](https://github.com/OutrightWings/treeplacer_mod/files/13910547/treeplacer_compat.zip)

**Comment by OutrightWings** [comment]
Absolutely I'll gladly take a look. What version of tree placer?

**Comment by OutrightWings** [comment]
So your datapack is incorrectly setup even if you wanted to do non treeplacer things! In your current setup, the directory to the oak_sapling.json is the following `treeplacer_compat/sapling_overrides/single/oak_sapling.json` It should be `treeplacer_compat/data/namespace/sapling_overrides/single/oak_sapling.json`

I could make the wiki more clear. I assumed people would know that all datapack related stuff starts with /name of datapack folder/data/namespace, as I just start with namespace.

**Comment by WenXin20** [comment]
Thanks, I had just figured that out and was about to post that! I had assumed that saplings_override was a replacement for the data folder. I had thought that was odd since I assumed it was listing the full path.
