### ISSUE TITLE
Does it randomize when the biome and sapling is the same?

### ISSUE THREAD

**Issue by WenXin20** [OutrightWings/treeplacer_mod#12]
Hello, one more question, when two tree features are set to the same biome for the oak sapling, does it randomize between the two or does it only pick the last entry? If it doesn't do this, could a way to randomize between the two be added? Currently, it seems to be only growing the last entry. 

```
{
   "replace": false,
   "values": {
      "biomesoplenty:mediterranean_forest": "biomesoplenty:sparse_oak_tree",
      "biomesoplenty:mediterranean_forest": "biomesoplenty:oak_bush"
   }
}
```

**Comment by OutrightWings** [comment]
It does indeed choose the last one. To have it be able to pick between them would require me to change how they are stored. My suggestion would be if you want to be able to have it pick between a few. Create a structure that does just that between your 3 or so tree types, and have that be the entry.

**Comment by WenXin20** [comment]
Ah, that's a good idea, thanks
