### ISSUE TITLE
I Updated Your Wythers' Datapack for Treeplacer

### ISSUE THREAD

**Issue by NonplussedUltra** [OutrightWings/treeplacer_mod#14]
Hi OutrightWings,
[treeplacer-wythers-1.20.1.zip](https://github.com/OutrightWings/treeplacer_mod/files/15391435/treeplacer-wythers-1.20.1.zip)

I'm NonplussedUltra, and I updated your Treeplacer datapack for William Wythers' to the 1.20.1 data format for my own server. I haven't changed any biome or feature references, so it's possible it's not 100% complete for WWEE 1.20.1. Nonetheless, it works for all the biomes I've checked out!

It is attached to this issue.

Thanks for making Treeplacer! It's a crucial supporting element for modern worldgen mods.

Regards,

NPUltra

**Comment by aMazeInRunar** [comment]
Hi! Do you know if this is also doable for Wythers Overworld Overhaul?

**Comment by NonplussedUltra** [comment]
> Hi! Do you know if this is also doable for Wythers Overworld Overhaul?

That is the mod this datapack is for! Beware that I haven't looked at this datapack since Minecraft 1.20.1, so if you're on a higher version, I can't guarantee it will work.
