### ISSUE TITLE
1.20.4 update?

### ISSUE THREAD

**Issue by vinnyg0621** [OutrightWings/treeplacer_mod#15]
hi any plans to update the mod to 1.20.4 or 1.20.6 or 1.21?

**Comment by OutrightWings** [comment]
Do you need the mod for said versions? If so I can make a version for whatever you need. Those aren't huge modding versions, 1.20.1 was, so I didn't go out of my way to make versions.

**Comment by vinnyg0621** [comment]
hold on, let me try on 1.20.4 to see if the 1.20.1 version works
