### ISSUE TITLE
treeplacer datapack version?

### ISSUE THREAD

**Issue by robtherobz** [OutrightWings/treeplacer_mod#17]
I assume this is not possible, but just figured I would ask!

**Comment by OutrightWings** [comment]
What are you asking?

**Comment by robtherobz** [comment]
Is there a way to make this mod into a datapack. I use WWOO as a datapack and am curious about the possiblity of using a tree-placer type plugin/datapack on a paper server, but I'm completely unfamiliar with mod making/datapack creation so forgive me if this is a silly question

**Comment by OutrightWings** [comment]
Iirc in the newest versions of the game I think you can alter sapling growth with datapacks. But nothing vanilla is going to be concise to a few files as my mod is. Beyond that. No. This is a mod. It changes the game's code, it can't just become a datapack.
