### ISSUE TITLE
(Question) Will this mod be Updated / Get more features

### ISSUE THREAD

**Issue by Cristelknight** [OutrightWings/treeplacer_mod#18]
Just asking because I'm thinking about including something like this or this in the WWOO / WWEE mods. 
If this won't get updated anymore I'll maybe continue it myself or make a new mod like this. Just wanting to know how it is going.

**Comment by OutrightWings** [comment]
Treeplacer I can update to any version people want--am I overlooking a wanted version? It's the datapacks for it that I don't have time to make. If people have feature requests I'm more than happy to add them. Thanks for the question. I made treeplacer originally for WW! Before it was updated and became too much for me to keep the datapacks to date.

**Comment by OutrightWings** [comment]
To be direct. I absolutely am keeping this mod up to date, I get questions from people all the time, helping them achieve/bug fix what they want. I just don't have ideas for features, hence there not being any new ones in a while.
