### ISSUE TITLE
1.21.1 - Neoforge - Trees dont grown without datapack

### ISSUE THREAD

**Issue by steelsicarius** [OutrightWings/treeplacer_mod#19]
Good morning,
I would like to report a problem with treeplacer for neoforge. Trees do not grow (For example, if you use treeplacer without any datapack for treeplacer, no trees will grow).

It only fails in version 1.21.1 for Neoforge.

In the fabric version it works correctly.

For now I use a small fix to have treeplacer in Neoforge: treeplacer-fabric-1.21.1-1.20.0 + Sinystra Connector + forgified-fabric-api

Thanks for your time and work! 
Sorry for my bad English ;)

**Comment by OutrightWings** [comment]
Thanks for the report! I'll take a look as soon as I can

**Comment by OutrightWings** [comment]
Issue found and fixed. Thanks for the report am publishing a fix right now.
