### ISSUE TITLE
wythers overhauled overworld not working 

### ISSUE THREAD

**Issue by ghost** [OutrightWings/treeplacer_mod#8]
the new mod wythers overhauled overworld is not working any way you can make it compatible?

https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld

**Comment by OutrightWings** [comment]
He completely overhauled the mod, as I'm sure you are aware. The current wythers addon is for the old version. I'll take a look at updating it for the new version- but it could take time. The original addon took me a few days! On Oct 12, 2023 2:45 AM, Thefatsparrow ***@***.***> wrote:
the new mod wythers overhauled overworld is not working any way you can make it compatible?
https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld

**Comment by ghost** [comment]
thank you!

**Comment by ghost** [comment]
hows the new overhauled mod going?

**Comment by OutrightWings** [comment]
In the base version, without all the extended biomes. There is a total of 103 various placed features (This does not equal the amount of trees as there can be more than 1 tree in each )called by 53 biomes. Its grueling work. And tbh I don't even play in 1.20, I'm a 1.19 player. So I've decided not to do this. I don't get paid, and Its really boring just going file after file after file.
